### ISSUE TITLE
Fix line breaking in listings.html

### ISSUE THREAD

**Issue by Tembrel** [jcip/jcip.github.com#11]
The use of the "yuk" symbol makes it hard to space the list items in `listings.html`. The current hack is:

````css
    <style>
      li {
        height: 28px;
        margin-top: 12px;
      }
      li.yuk::after {
        position: absolute;
        content: url('images/mryuk.gif');
      }
    </style>
````
but it could certainly be improved, especially for small screens.
